version: "3"

services:
  nodejs:
    image: tdgihp4c/backend:v22
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network
  
  webapp:
    image: tdgihp4c/angular-app:v28
    container_name: webapp
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - webserver
    networks:
      - app-network

volumes:

  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/egoverment/node_project/views/
      o: bind

networks:
  app-network:
    driver: bridge
