version: "3"

services:
  nodejs:
    image: tdgihp4c/backend:v20
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:

  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/egoverment/node_project/views/
      o: bind

networks:
  app-network:
    driver: bridge
